# Generated by Django 5.1.7 on 2025-03-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vehicletype_location_audiodetection_recommendation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
