# Generated by Django 5.1.7 on 2025-03-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodetection',
            name='location',
        ),
        migrations.RemoveField(
            model_name='audiodetection',
            name='sound_type',
        ),
        migrations.RemoveField(
            model_name='audiodetection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='detection',
        ),
        migrations.RemoveField(
            model_name='drivinghistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='history',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehiclesensor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='visualdetection',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='visualdetection',
            name='user',
        ),
        migrations.DeleteModel(
            name='SoundType',
        ),
        migrations.DeleteModel(
            name='AudioDetection',
        ),
        migrations.DeleteModel(
            name='DrivingHistory',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='VehicleSensor',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
        migrations.DeleteModel(
            name='VisualDetection',
        ),
    ]
